### ISSUE TITLE
Docs badge is broken 

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaStats/StatsModels.jl#102]
I just clicked the docs badge in the readme (5/9/2019) and it links to this page https://juliastats.github.io/StatsModels.jl/latest which gives a 404 page missing error. Where are the hosted docs supposed to be?

**Comment by kleinschmidt** [comment]
I think we just need to trigger a rebuild of the docs since this repo was accidentally deleted...not sure how to do that besides pushing a commit to master...

**Comment by jpfairbanks** [comment]
Should I change something in the readme to trigger the rebuild?

**Comment by kleinschmidt** [comment]
Should be good now.
