### ISSUE TITLE
Updating to the new version of StatsModels

### ISSUE THREAD

**Issue by matthieugomez** [JuliaStats/StatsModels.jl#124]
I am trying to update to the new StatsModels for FixedEffectModels. There are two things that I would need help with. I am posting this as an issue, in case this cannot be done with the current version of StatsModels. 

The first thing is: how get the rows of a DataFrame for which all the variables used in the formula (or their transformation) are non missing?
I used to do:
```julia
get_nonmissing_rows(f::Formula) = completecases(allvars(f))
```

The second thing: how to construct a ModelDataFrame only for a subsample of the data (prespecified by the user)? I used to do:
```julia
function MyModelFrame(trms::Terms, d::AbstractDataFrame, esample; contrasts::Dict = Dict())
	df = DataFrame(map(x -> d[x], trms.eterms), Symbol.(string.(trms.eterms)))
	if !all(esample)
		df = df[esample, :]
	end
	evaledContrasts = evalcontrasts(df, contrasts)
	check_non_redundancy!(trms, df)
	ModelFrame(df, trms, esample, evaledContrasts)
end
```

Note that both functions were somewhat memory-efficient (i.e. they did not need to create intermediary objects). Is there a way to do the same in the new version of StatsModels?

**Comment by Nosferican** [comment]
I think the following is equivalent to `dropmissing(data[allvars(fm)], true)`
```
pns = termvars(f)
data = data[pns]
data = data[map(row -> all(!ismissing(getproperty(row, pn)) for pn ∈ pns),
                rows(data)),:]
foreach(pn -> data[pn] = disallowmissing(data[pn]),
        propertynames(data))
```
so rather than making a `ModelFrame`, you should use the
`model_response, model_features = modelcols(fm, data)`.

Feel free to look at the code in https://github.com/Nosferican/Econometrics.jl (it was developed for StatsModels `v"0.6"`).

**Comment by matthieugomez** [comment]
Thanks @Nosferican . I will post any remaining issue in the discourse thread about the new package.

**Comment by kleinschmidt** [comment]
IMO these operations are best left to a Tables.jl package (maybe @quinnj's TableOperations but that hasn't been updated for a few months so I don't know the status or long-term plans).

For the first, there's an (internal, un-exported, may change in the future without warning) function called `missing_omit` that does that operation: https://github.com/JuliaStats/StatsModels.jl/blob/master/src/modelframe.jl#L46-L78

For the second that really is a table-specific operation.  Note that in your example you're creating new vectors for every column; you could always do a view operation but, again, this is something that's best handled on the Tables.jl end of things.
