### ISSUE TITLE
Update StatsModels.jl to new DataFrames.jl 0.19 release

### ISSUE THREAD

**Issue by bkamins** [JuliaStats/StatsModels.jl#132]
The change is that `df[col]` now should be written as `df[!, col]` (otherwise a deprecation warning is printed currently).

I can help fixing this, but I am not sure what is the release schedule of this package (also against GLM.jl). The issue is that this change is breaking (i.e. it is not backwards compatible with DataFrames.jl 0.18, so maybe you prefer to check a version of DataFrames.jl installed for some time).

**Comment by kleinschmidt** [comment]
DataFrames is only used for tests here so should be fine to bump the version compat and wait for the next release.

**Comment by bkamins** [comment]
You are right indeed 😄.

I am preparing a DataFrames.jl tutorial for JuliaCon and for some strange reason having StatsKit.jl installed kept GLM.jl and StatsModels.jl pinned to older versions that had this dependency.

Thank you for such a fantastic design (after unpinning GLM.jl works cleanly with DataFrames.jl 0.19 without any problems).
