### ISSUE TITLE
one sided formulae no longer work

### ISSUE THREAD

**Issue by clintonTE** [JuliaStats/StatsModels.jl#143]
Use case is to extract the matrix implied by the RHS without providing the response.

```Julia
using StatsModels, DataFrames

function mwe(N=1000)
  df = DataFrame(x = rand(N))
  LHS::Nothing, RHS = nothing, :x

  f = @eval(@formula($LHS ~ $RHS))
  mf::ModelFrame = ModelFrame(f, df)
end

mwe()
```

OUTPUT:
```Julia
ERROR: LoadError: MethodError: no method matching ~(::Nothing, ::Term)
Closest candidates are:
  ~(::Union{AbstractTerm, Tuple{Vararg{AbstractTerm,N}} where N}, ::Union{AbstractTerm, Tuple{Vararg{AbstractTerm,N}} where N}) at C:\Users\Clinton\.julia\packages\StatsModels\EgmMO\src\terms.jl:397
Stacktrace:
 [1] top-level scope at C:\Users\Clinton\Dropbox\Projects\LeverageChanges\src\test.jl:104
 [2] eval at .\boot.jl:330 [inlined]
 [3] mwe(::Int64) at C:\Users\Clinton\Dropbox\Projects\LeverageChanges\src\test.jl:100
 [4] mwe() at C:\Users\Clinton\Dropbox\Projects\LeverageChanges\src\test.jl:97
 [5] top-level scope at C:\Users\Clinton\Dropbox\Projects\LeverageChanges\src\test.jl:104
in expression starting at C:\Users\Clinton\Dropbox\Projects\LeverageChanges\src\test.jl:104
```

Other info:
Writing nothing instead of $LHS in the formula doesn't work either, but gives a different error message (`ERROR: LoadError: type NamedTuple has no field nothing`).

Replacing the LHS with `identity(1)` works sort of, but has a 10x performance impact. A higher performance work around would be great!

Windows 10
Julia 1.2
StatsModels 6.3
DataFrames 19.3

EDIT: This used to work in StatsModels 0.5
EDIT2: Just saw the pull requests #20 and #139. Feel free to close, or consider what I am doing a use case-- I use the matrix extraction for a bunch of bespoke regression code.

**Comment by kleinschmidt** [comment]
Yeah once you've generated the concrete formula (with `apply_schema`) you can just call `modelcols` on it.  I'm closing this since one-sided formulas using 0 are documented with #155
