### ISSUE TITLE
breaking changes to contrasts

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaStats/StatsModels.jl#175]
To be considered for the next breaking release (as discussed briefly in #172):

- [ ] use keyword arguments for contructors
- [ ] error on missing labels for hypothesis/contrasts coding
- [ ] more specific termnames for contrasts

**Comment by palday** [comment]
xref #251 -- we should probably support arbitrary matrix containers and eltypes to allow e.g. sparse matrices in single precision.

**Comment by ararslan** [comment]
AFAICT that shouldn't actually be breaking though.

**Comment by palday** [comment]
@ararslan I mostly agree, changes to the type parameters (and I suspect that we should maybe have the storage type as a type parameter) can have all sorts of wonky knock-on effects even if most code will run without change.
