### ISSUE TITLE
Tag a version

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/StatsModels.jl#18]
It would help me a lot with testing [IterableTables](https://github.com/davidanthoff/IterableTables.jl) if we could tag a new version here that reflects the use of ``DataTable`` instead of ``DataFrame``. Just current ``master`` would be fine. I think if the version was ``0.0.2``, it would still indicate that there is no proper first release.

**Comment by ararslan** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/8586

**Comment by nalimilan** [comment]
Wow, fast!

**Comment by davidanthoff** [comment]
Thanks!
