### ISSUE TITLE
Shifted columns?

### ISSUE THREAD

**Issue by animBreedTools** [JuliaStats/StatsModels.jl#180]
I have the following code for the example data from a textbook (Mrode et al., Linear Models for the Prediction of Animal Breeding Values).

```
using DataFrames, MixedModels, StatsModels

data = DataFrame()
data.Calf  = string.(collect(5:14))
data.Sire  = [1,3,4,3,1,3,3,8,9,3]
data.Dam   = [2,2,6,5,6,2,7,7,2,6]
data.Herds = [1,1,1,1,2,2,2,3,3,3]
data.Pen   = [1,2,2,1,1,2,2,2,1,2]
data.BW    = [35.0,20.0,25.0,40.0,42.0,22.0,35.0,34.0,20.0,40.0]

f = @formula(BW ~ 1 + Herds + Pen + (1|Calf))

f_sch = apply_schema(f, schema(data,Dict(:Herds => StatsModels.FullDummyCoding(),:Pen => StatsModels.FullDummyCoding())), MixedModel)

y, (X, Z) = modelcols(f_sch, data)
```

When I check the Z matrix, the columns are shifted, not matching the order of y. I could not see why this is the case.

**Comment by palday** [comment]
How do you mean the columns are shifted? The columns are just indicator variables -- more important is that the rows match. Looking at Z, I get:
```
julia> Z
10×10 ReMat{Float64,1}:
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0

julia> Z.adjA
10×10 SparseMatrixCSC{Float64,Int32} with 10 stored entries:
  [6 ,  1]  =  1.0
  [7 ,  2]  =  1.0
  [8 ,  3]  =  1.0
  [9 ,  4]  =  1.0
  [10,  5]  =  1.0
  [1 ,  6]  =  1.0
  [2 ,  7]  =  1.0
  [3 ,  8]  =  1.0
  [4 ,  9]  =  1.0
  [5 , 10]  =  1.0
```

In other words, one occurrence of each indicator level, which matches the data you have with one observation per Calf.

**Comment by animBreedTools** [comment]
But this Z tells that observation 1 (35.0) belongs to 6th individual (Calf with ID 10 instead of 1), which is not right. Whereas X matrix follows the same order in y. Setting up with right X and column shuffled Z will be different for:

`[X'X X'Z;
   Z'X Z'Z + I] B = [X'y;Z'y]`

**Comment by animBreedTools** [comment]
That Z indicates that observation 1 belongs to individual 6, which is not right. X follows the order in y, whereas Z does not, because columns are shuffled. This will lead different solutions in:

[X'X X'Z ; Z'X Z'Z + I*0.02] b = [X'y ; Z'y]

`julia> using LinearAlgebra, Random

julia> Z
10×10 ReMat{Float64,1}:
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0

julia> inv([X'X X'Z ; Z'X Z'Z + Matrix(0.02I,10,10)])*[X'y ; Z'y]
16-element Array{Float64,1}:
  50.988853874885315
   1.2284663865616494
  48.13322829132426
  13.466561624659285
 156.49696545284013
 -60.93160597572424
  -9.010270774976505
   3.734827264238959
   4.388422035481199
 -14.659197012138065
  10.27077497665772
   2.240896358543523
  -7.14285714285711
  -2.240896358543523
   7.142857142856883
   5.275443510737659

julia> Z = Matrix(1.0I,10,10)
10×10 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

julia> inv([X'X X'Z ; Z'X Z'Z + Matrix(0.02I,10,10)])*[X'y ; Z'y]
16-element Array{Float64,1}:
   38.51231325863921
  -51.34401260503488
  -75.29639355741972
 -119.96306022407862
  -55.02544351074414
   55.68884220354727
    2.240896358543438
   -7.142857142857338
   -2.240896358543523
    7.142857142857451
    5.275443510737318
   -9.010270774976675
    3.7348272642390157
    4.388422035481426
  -14.65919701213852
   10.270774976658004`

**Comment by palday** [comment]
I'm going to channel @dmbates for a moment: if you have to do an explicit matrix inverse in numerical linear algebra, you're probably doing it wrong. In this particular case, let's look at the actual MixedModel:

```
julia> mod = fit(MixedModel, f, data)
Linear mixed model fit by maximum likelihood
 BW ~ 1 + Herds + Pen + (1 | Calf)
   logLik   -2 logLik     AIC        BIC    
 -34.776435  69.552869  79.552869  81.065794

Variance components:
            Column    Variance  Std.Dev. 
Calf     (Intercept)  52.931034 7.2753718
Residual               8.468966 2.9101487
 Number of obs: 10; levels of grouping factors: 10

  Fixed-effects parameters:
──────────────────────────────────────────────────
             Estimate  Std.Error  z value  P(>|z|)
──────────────────────────────────────────────────
(Intercept)  37.3333     9.59687     3.89   0.0001
Herds         1.22222    3.01601     0.41   0.6853
Pen          -5.22222    5.11389    -1.02   0.3072
──────────────────────────────────────────────────

julia> fitted(mod)
10-element Array{Float64,1}:
 34.77011494252877
 21.118773946360154
 25.42911877394636
 39.08045977011498
 40.973180076628374
 23.01149425287355
 34.21839080459769
 33.52490421455937
 22.176245210727988
 38.69731800766282

julia> data.BW
10-element Array{Float64,1}:
 35.0
 20.0
 25.0
 40.0
 42.0
 22.0
 35.0
 34.0
 20.0
 40.0
```
(Note that this isn't a great example: you have only one observation per Calf.)

So the fitted values correspond pretty well to the observed values, which suggests that the Z matrix isn't being flipped.

**Comment by palday** [comment]
I think you're missing that some 'sorting' is done in constructing Z and that this is tracked in Z:
```
julia> data.Calf
10-element Array{String,1}:
 "5"
 "6"
 "7"
 "8"
 "9"
 "10"
 "11"
 "12"
 "13"
 "14"

julia> Z.levels
10-element Array{String,1}:
 "10"
 "11"
 "12"
 "13"
 "14"
 "5"
 "6"
 "7"
 "8"
 "9"
```

**Comment by palday** [comment]
(I'm not trying to be difficult, but we have lots of tests for MixedModels, which are verified against other software packages and this suggests that we're not messing up the model matrices too much, but rather that the interpretation of the Z matrix is the problem here.)

**Comment by animBreedTools** [comment]
I am neither inverting those matrices in practice, nor this is the point of discussion here. The above code is just to provide a toy example, where the order of columns matters.

**Comment by palday** [comment]
My point is that the order does not mean what you think it does -- the column ordering corresponds to `Z.levels` not the original ordering in the data. The position within each column of the indicator does of course correspond to the original data.  Level `5` is the first observation in the data, but the 6th column in Z (as shown in `Z.levels`). This corresponds to the Z matrix, where the 6th column has an indicator in the first row, meaning that level `5` is the first observation:

```
julia> Z[:, 6]
10-element Array{Float64,1}:
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

julia> Z.levels[6]
"5"
```

**Comment by animBreedTools** [comment]
I get it that it is conserved between ```Z``` and ```Z.levels```, but when I print out y,X and Z with
```
y, (X, Z) = modelcols(f_sch, data)
```
the orders are different, and not conserved between y,X and Z. The example I provided clearly shows the difference. Maybe something wrong with ```modelcols()```?

**Comment by kleinschmidt** [comment]
I think the confusion here is coming from the fact that in Statsmodels, the order of levels of a categorical variable is intentionally NOT based on the order of occurrence in the data (intentionally), but rather on lexical ordering, and "10" (a string) comes before "5" because "1" comes before "5" (just like "az" would sort before "y"). 

Its the level order that determines the column order, not the row order in the data. Think about what would happen if you had multiple rows from the same groups interspersed with other groups throughout the table...

**Comment by animBreedTools** [comment]
@kleinschmidt I got the point. Though I don't see what is the benefit of internally re-ordering the levels, rather arbitrarily... Thank you.

**Comment by kleinschmidt** [comment]
In most contexts, lexical ordering seems to better match folks' expectations than order of appearance (which in actual data is often totally random or arbitrary); I see why it seems confusing here but this is the first such instance I can recall of confusion about it.  In part the confusion is also due to converting from a number (where the lexical sort will give you a sensible ordering) to a string (where the lexical sort will not).

It matters more for contrast coding categorical variables where the first level is usually treated as a baseline, and in other statistical packages that first level is usually defined based on lexical order, not order of appearance.  Another benefit is that in a regression model, the ordering (and the values) of the coefficients is going to be invariant under shuffling the data rows.

Also, if you really care about the ordering of the levels you can convert the column into a `CategoricalArray` for which you can define whichever ordering of levels you want, and that will be respected.
