### ISSUE TITLE
no method matching +(::InterceptTerm{true})

### ISSUE THREAD

**Issue by matthieugomez** [JuliaStats/StatsModels.jl#207]
The following snippet runs in v0.6.15 but returns an error in v0.6.16
```julia
using StatsModels
d = (a = [1,1],)
apply_schema((ConstantTerm(1),), schema(d))
# MethodError: no method matching +(::InterceptTerm{true})
```
This change breaks the tests in [FixedEffectModels](https://github.com/FixedEffects/FixedEffectModels.jl), even though it was introduced in a minor version. Would it be possible to fix it?

**Comment by palday** [comment]
@matthieugomez That definitely wasn't intended. Can you check whether #208 fixes all your problems?

**Comment by matthieugomez** [comment]
Yes, the tests work again with this new pull request. Thank you so much!

**Comment by kleinschmidt** [comment]
JuliaRegistries/General#28286 - 0.6.19 should be good to go.
