### ISSUE TITLE
Abbreviations in attribute names

### ISSUE THREAD

**Issue by jtrakk** [JuliaStats/StatsModels.jl#210]
I don't always remember what the abbreviations stand for and I have to go back to the docs frequently. It would be easier to understand if `.mf` were replaced with `.modelframe`, for example.

**Comment by palday** [comment]
I think part of the motivation here is that the public API is largely defined by methods and not fields. For example `model_response`, `modelcols` and `modelmatrix` provide accessors for those internal fields.

(There are some members of the community who think that the API should be exclusively defined by methods and the type hierarchy and that the details of any given `struct` should always be considered private implementation details.)
