### ISSUE TITLE
method for human to make formula with FunctionTerm 

### ISSUE THREAD

**Issue by PharmCat** [JuliaStats/StatsModels.jl#232]
Method for human to make formula with FunctionTerm in expression. 

I try to make dynamic formula like this:

```
module XXX
using StatsModels
global i = Symbol()
for  v in [:a, :b]
    i = v
    model = eval(:(
    StatsModels.capture_call(log, (($i,)->log($i)),
    (i,),
    $(Expr(:copyast, :($(QuoteNode(:(log($i))))))),
    [StatsModels.Term(i)]
    )
    ~ Term(:AX)))
#some code with lm()
end
end
```

for simple Term it easy:

```
:(Term(:y) ~ ConstantTerm(1) + Term(:a) + Term(:b) + Term(:a) & Term(:b))
```

at the end i get:

```
ERROR: MethodError: no method matching (::Main.XXX.var"#7#8")(::Float64)
The applicable method may be too new: running in world age 30095, while current world is 30096.
```

**Comment by ndgnuh** [comment]
My current workaround:

```julia
function single_functional_term(f, x)
	symbol = Expr(:call, Symbol(f), x)
	fanon = eval(:(($x,) -> log($x)))
	StatsModels.capture_call(f, fanon, (x,), symbol, [Term(x)])
end

f = let res = Term(:y)
	pres = mapreduce(vcat, 1:3) do i
		s = Symbol("x$i")
		[Term(s), single_functional_term(log, s)]
	end
	FormulaTerm(res, (pres...,))
end
```

It doesn't work on multiple arity functions though, like `(x, y) -> log(x*y)`

**Comment by kleinschmidt** [comment]
See #183 ... with that proposal you can construct them a lot more easily since there's no need for an anonymous function.

For now I'd suggest using @ndgnuh solution, except you can do `@eval(@formula(0 ~ $expr)).rhs` (use `0` on the LHS)

**Comment by kleinschmidt** [comment]
There's definitely no reason to deal with `capture_call` directly, that's just to make the macro itself a bit cleaner to write :)  Once you're doing any kind of `eval` you might as well use `@formula`

**Comment by PharmCat** [comment]
> 

seems second case not working with GLM

**Comment by kleinschmidt** [comment]
#183 is merged and there are examples in the tests of how to create function terms programatically!
