### ISSUE TITLE
Different String Types in Levels

### ISSUE THREAD

**Issue by palday** [JuliaStats/StatsModels.jl#236]
With the release of CSV 0.9, the default string type being read in is `InlineString`, which leads to problems when levels for contrast codings are specified as `String`. It feels like it would be nice to allow this comparison (or possibly for subtypes of `AbstractString`).

**Comment by kleinschmidt** [comment]
It seems like this is something that would be best handled upstream, since we're using a `Dict{typeof(level),Int}` to look up row of the contrasts matrix and that won't work without hash equality.  I guess we could `convert` the data to the type of the levels before checking but that seems like a big potential footgun...

**Comment by kleinschmidt** [comment]
Actually, this might be solvable at schema time, since we're comparing the unique values in the data with the levels.  But the problem is still the same...either have to get `==` to be true or do conversion.  But at least you're not `convert`ing every time you call `modelcols`

**Comment by palday** [comment]
Yeah, it might be nice for `==` between `String` and `InlineString` to work (much like equality works between subtypes of `Number`, to the extent that exact equality is meaningful.)

**Comment by kleinschmidt** [comment]
Looks like it already should: 

https://github.com/JuliaData/WeakRefStrings.jl/blob/main/src/inlinestrings.jl#L216-L223

**Comment by palday** [comment]
Is it the `sizeof` that's causing problems? Naively, I would think that should be `length`

**Comment by ararslan** [comment]
AFAICT, that shouldn't adversely affect anything here. Note for example
```julia
julia> s = "你好"
"你好"

julia> length(s)
2

julia> sizeof(s)
6
```
If you're comparing two string-like things and you want a fast path to ensure they have the same size/length/whatever, `sizeof` seems more correct, since you'll return `false` early for e.g. `"你好" == InlineString("hi")`.

**Comment by kleinschmidt** [comment]
I think the issue for us is that we're checking whether the eltypes match for the contrasts levels and the data levels.  We need a weaker check, that they're set equal or something.

**Comment by palday** [comment]
There's already a set equal check after the eltype check, maybe we just turn the eltype check into a warning and special case subtypes of `AbstractString`  so that it doesn't warn in that one case?

(for quick reference here's the eltype check: https://github.com/JuliaStats/StatsModels.jl/blob/7a377cdfc8a028aa38a861d90d3c272004646148/src/contrasts.jl#L169-L172)
