### ISSUE TITLE
`base` argument in `SeqDiffCoding()` does not seem to work as expected

### ISSUE THREAD

**Issue by HaiyangJin** [JuliaStats/StatsModels.jl#237]
When `base` is set with the non-first level in the alphabetic order of the variable, it seems still to use the first level as the `base`. 

For example:
```julia
using StatsModels, DataFrames, GLM # StatsModels version: v0.6.25

df = DataFrame(IV = ["a", "b", "a", "b"],
               DV = [2, 3, 2, 5])
```

### Set `base = "a"`:
```julia
base_a = fit(LinearModel, @formula(DV ~ IV), df, 
                      contrasts=Dict(:IV => SeqDiffCoding(base = "a")))
```
```
────────────────────────────────────────────────────────────────────
             Coef.  Std. Error     t  Pr(>|t|)  Lower 95%  Upper 95%
────────────────────────────────────────────────────────────────────
(Intercept)    3.0         0.5  6.00    0.0267   0.848674    5.15133
IV: b          2.0         1.0  2.00    0.1835  -2.30265     6.30265
────────────────────────────────────────────────────────────────────
```

### Set `levels = ["a", "b"]`
```julia
level_ab = fit(LinearModel, @formula(DV ~ IV), df, 
                       contrasts=Dict(:IV => SeqDiffCoding(levels = ["a", "b"])))
```
```
────────────────────────────────────────────────────────────────────
             Coef.  Std. Error     t  Pr(>|t|)  Lower 95%  Upper 95%
────────────────────────────────────────────────────────────────────
(Intercept)    3.0         0.5  6.00    0.0267   0.848674    5.15133
IV: b          2.0         1.0  2.00    0.1835  -2.30265     6.30265
────────────────────────────────────────────────────────────────────
```
### Set `base = "b"`:
```julia
base_b = fit(LinearModel, @formula(DV ~ IV), df, 
                       contrasts=Dict(:IV => SeqDiffCoding(base = "b")))
```
```
────────────────────────────────────────────────────────────────────
             Coef.  Std. Error     t  Pr(>|t|)  Lower 95%  Upper 95%
────────────────────────────────────────────────────────────────────
(Intercept)    3.0         0.5  6.00    0.0267   0.848674    5.15133
IV: a          2.0         1.0  2.00    0.1835  -2.30265     6.30265
────────────────────────────────────────────────────────────────────
```
### Set `levels = ["b", "a"]`
```julia
level_ba = fit(LinearModel, @formula(DV ~ IV), df, 
                       contrasts=Dict(:IV => SeqDiffCoding(levels = ["b", "a"])))
```
```
─────────────────────────────────────────────────────────────────────
             Coef.  Std. Error      t  Pr(>|t|)  Lower 95%  Upper 95%
─────────────────────────────────────────────────────────────────────
(Intercept)    3.0         0.5   6.00    0.0267   0.848674    5.15133
IV: a         -2.0         1.0  -2.00    0.1835  -6.30265     2.30265
─────────────────────────────────────────────────────────────────────
```
As expected, the results of `base_a` matched those of `level_ab`. However, `base_b` results do not match `level_ba`. It seems that the results of `base_b` are not correct.

**Comment by kleinschmidt** [comment]
Thanks for reporting this.  Gave me a brief heart attack before I realized it was SeqDiffCoding...I agree that the handling of base vs. levels is confusing here.  From the `contrasts_matrix` method, you can see that the base index argument is totally ignored, so only `levels` actually matters, which is consistent with the behavior you're reporting.  I think it makes sense to add a warning to this effect if someone specifies `base` (especially along with `levels`), and to either deprecate the base kwarg altogether or to do some gymnastics where the base level gets moved to the front the vector of levels.  I'd lean towards the deprecation since if you're specifying the base then we probably want to you to specify the full order to avoid surprises.

**Comment by HaiyangJin** [comment]
Thanks for the explanation. Deprecation of `base` sounds good to me. It was not clear to me what `base` refers to in `SeqDiffCoding` so tested it with some simulated data. BTW, I also tested with other contrast coding and the `base` kwarg works as expected.
