### ISSUE TITLE
Names of coefficients do not match those of columns

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/StatsModels.jl#24]
I am using Julia 0.6-rc2 with StatsModels.jl + DataTables.jl.

```
df = readtable("NLS.csv"); # Same as DataFrames.readtable(IO, DataTable)
formula = @formula(ln_wage ~ age + race) # StatsModels.Formula
df = df[:, StatsModels.allvars(formula)] # DataTables.DataTable
df = df[completecases(df), :]
df[:race] # NullableArrays.NullableArray{WeakRefStrings.WeakRefString{UInt8},1}
mf = StatsModels.ModelFrame(formula, df)
mm = getfield(StatsModels.ModelMatrix(mf), :m)
y = Array{Float64,1}(df[formula.lhs])
β = inv(cholfact(mm' * mm)) * mm' * y
Names = StatsModels.coefnames(mf)
output = DataTable(Feature = Names, β = β)
```
The names of the covariates for the nominal variable are not in the correct order to match those of the coefficient estimates.

One can visually confirm the bug my inspecting the design matrix `mm`.
```
Names[3:4]
mm[find(df[:race] .== Names[3])[1:5], 3:4]
```

**Comment by ararslan** [comment]
As a disclaimer, DataTables is considered experimental and StatsModels isn't registered and thus isn't yet intended for general use. I recommend trying this in DataFrames, which still contains modeling functionality. (Also, no space between `@formula` and the parentheses.)

**Comment by Nosferican** [comment]
DataFrames does not currently support creating a ModelMatrix out of string variables. One has to first manually transform the variable through `pool!(df, [:var])` and then use the mutated df through the pipeline. I suspect since `StatsModels` does the transformation automatically for `DataTables` from `String` or even `WeakRefStrings.WeakRefString{UInt8}` somewhere in that process it gets messed up.

**Comment by Nosferican** [comment]
Seems to be resolved in the latest version.
