### ISSUE TITLE
Export hasintercept and omitsintercept?

### ISSUE THREAD

**Issue by matthieugomez** [JuliaStats/StatsModels.jl#276]
Because they are not exported, I am redefining both in FixedEffectModels. It might be useful for other packages as well.

**Comment by ararslan** [comment]
I believe a number of packages are assuming they're public, e.g. GLM and Survival off the top of my head, so definitely +1 for exporting.

**Comment by kleinschmidt** [comment]
yeah we shoudl be exporting these
