### ISSUE TITLE
Extending @formula syntax is difficult to understand

### ISSUE THREAD

**Issue by yanyu2015** [JuliaStats/StatsModels.jl#292]
Extending @formula syntax is difficult to understand.   
I read the examples of `ploy` in the official documentation, but I feel that the comments are not detailed enough, and I still don't quite understand.   
For example, why define `StatsModels.apply_schema`, and after defining it, how is it called in `f = apply_schema(f, schema(data))` ? Can you give a detailed and clear procedure?

**Comment by kleinschmidt** [comment]
Dear @yanyu2015, issues are really only meant for reporting bugs, requesting features, etc.

For support requests like this, please use https://discourse.julialang.org/, the julia slack https://julialang.org/slack/, or another community forum https://julialang.org/community/!
