### ISSUE TITLE
Missing allvars?

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/StatsModels.jl#34]
I was a fan of `DataFrames.allvars` for obtaining all variables from a `Formula`. I noticed it was missing from StatsModels. Was this intentional? I believe it to be a pretty essential functionality that would be a useful to have for our development and for other packages developers. Was there a reason to get rid of it?

**Comment by nalimilan** [comment]
Not sure, but at least we could find a better name? Is "all" really needed?

**Comment by Nosferican** [comment]
I actually like the name... What about `varlist` as it differs from `coefnames` which are used in the context of right-hand side?

**Comment by kleinschmidt** [comment]
I think the reason was that it didn't appear to be used :)  But there's no harm in having it if it'll be useful.  You can get similar information from the `Terms` struct, too (it's probably the `eterms` field you want).

**Comment by kleinschmidt** [comment]
(but since I'm dreaming of changing the internal representation it's probably better to have a accessor method like allvars)

**Comment by kleinschmidt** [comment]
I'd go with just `vars` over `varlist`...

**Comment by Nosferican** [comment]
My hesitation with `vars` is that there is a higher chance of people using vars... Still I always classify my variables so it wouldn't affect me :). Another benefit of an accessor is that it could allow for easy access to other structs... For example,
Let us assume, 
```
abstract type Formulae end
struct formula <: Formulae
    lhs::Union{Symbol, ...}
    rhs::Union{...}
end
mutable struct MyCustomFormula
    Main::Formula
    Secondary::Formula
end
function vars(formula::Formulae)
    getfield(formula, :eterms)
end
function vars(MyCustomFormula)
    union(vars(MyCustomFormula.Main, MyCustomFormula.Secondary))
end
```
or even better define it as the recursive union of all fields that are `Formulae` for example... +1 for accessor methods.

**Comment by kleinschmidt** [comment]
I imagine this isn't something we'd export (since it's primarily useful for people developing against this package, not end users) so I'm not so worried about the potential ambiguity...

**Comment by Nosferican** [comment]
Sounds good I will submit a pull request which basically brings it back with the same code that was used in `DataFrames/statsmodels`. Should `Formula` be a child of `Formulae` or something now that there will be different types of formulas (e.g., `OneSided`, `TwoSided`, and custom ones which will require different methods, etc.)?

**Comment by nalimilan** [comment]
Why not `variables`? We usually prefer using explicit names when they are not too long.

**Comment by kleinschmidt** [comment]
Let's keep the `variables`/`allvars` changes separate from any formula redesigns...

**Comment by Nosferican** [comment]
Given that it is easier now to select all the terms than what it was in the past and the future redesign I am closing this issue.

**Comment by youngjaewoo** [comment]
I can't quite follow how to use `variables / allvars`. However, is there an equivalent to R's use of "." to select all columns for the model?

e.g. glm(:(outcome ~ .), df, Bernoulli());

referencing https://github.com/JuliaStats/GLM.jl/issues/18
