### ISSUE TITLE
Bug with categorical arrays with difference in distinct and levels

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/StatsModels.jl#36]
Using the latest release of CategoricalArrays, `ModelMatrix` fails if
```
obj::CategoricalArrays.AbstractCategoricalVector
length(unique(obj)) ≠ length(DataFrames.levels(obj))
```
I believe the issue is in `modelmat_cols`.
A possible fix for now is
```
function rebase(obj::CategoricalArrays.AbstractCategoricalVector{T}) where T
    if length(unique(obj)) ≠ length(levels(obj))
        output = CategoricalArrays.CategoricalVector{T}(convert.(eltype(levels(obj)), obj))
    else
        output = obj
    end
    return output
end
obj = rebase(obj)
```
and that allows `ModelMatrix` to work properly.

**Comment by kleinschmidt** [comment]
What does "fails" mean? There's an error?

**Comment by Nosferican** [comment]
Sorry, missed the error message.
```
BoundsError: attempt to access m×(m - 1) Array{Float64,2} at index ...
```
where `m = length(unique(obj))`

**Comment by nalimilan** [comment]
Could you post a simple reproducer?

**Comment by Nosferican** [comment]
It seems to work on some cases and break on others. I will keep trying to identify the conditions. I was using the NLS data set (nlswork from Stata). Once I figure out what triggers it I will post a reproducer.

**Comment by Nosferican** [comment]
Here is a [gist](https://gist.github.com/Nosferican/c141036301f9835ef0c84ca071384f49) with the code. Let me know if you want a copy of the Feather file.

**Comment by nalimilan** [comment]
Thanks, but it would be useful to have a simplified data set, ideally only with a few lines. Also, why do we need the JuliaEconometrics forks of the packages?

**Comment by Nosferican** [comment]
I tried to replicate it with dummy dataframes like
`df = DataFrame(x = repeat(["a", "b", "c"], inner = 3), y = Vector{Union{Nulls.Null, Int64}}(1:9))`, but it does not replicate. The only case for which I have been able to experience the bug was using that data set and steps. Maybe, y'all can figure out what is the cause by replicating it with other data sets to diagnose it.
The forks are not needed. Currently in order to get StatsModels to precompile and work with DataFrames in Julia 0.7 it needs some adjustments (mainly the port from DataTables to DataFrames PR). I applied that one and some depreciation stuff to get it to work. I provide them in the off chance something there could be the cause of the bug.

**Comment by nalimilan** [comment]
Have you tried calling `levels!` on `CategoricalArray` columns to add unused levels?

**Comment by Nosferican** [comment]
I have
`CategoricalArrays.CategoricalArray{String,1,UInt32,String,Union{}}`
calling `levels!`
```
MethodError: no method matching levels!(::CategoricalArrays.CategoricalArray{String,1,UInt32,String,Union{}})
Closest candidates are:
  levels!(::CategoricalArrays.CategoricalArray{T,N,R,V,U} where U where V where R<:Integer where N, ::Array{T,1} where T; nullok) where T at /.julia/v0.7/CategoricalArrays/src/array.jl:545
  levels!(::CategoricalArrays.CategoricalPool{S,R,V}, ::Array{T,1} where T) where {S, R, V} at /.julia/v0.7/CategoricalArrays/src/pool.jl:139
```

**Comment by nalimilan** [comment]
Have a look at the docstring...
