### ISSUE TITLE
Setting base level of categorical variables has no effect

### ISSUE THREAD

**Issue by lbittarello** [JuliaStats/StatsModels.jl#39]
It seems that setting the base level of categorical variables has no effect on the final `ModelMatrix`. I've tried setting the base level via the `contrasts` keyword to `ModelFrame` and via `levels!`. Both strategies do change the `ConstrastsMatrix` in the `ModelFrame`, so the problem must be the transformation of the `ModelFrame` into a `ModelMatrix`. I believe that lines 68-70 in `modelmatrix.jl` are the culprit, because they reorder the levels of and recode the categorical variable. Perhaps you want to add a line like `reindex = contrast.levels[reindex]` after line 68.

**Comment by nalimilan** [comment]
Good catch, thanks. I think we just need to replace `levels(v)` with `CategoricalArrays.index(v)`, since the integer codes refer to the latter.

Since you appear to have investigated the problem a bit, would you be willing to make a pull request with a test which currently fails?

**Comment by lbittarello** [comment]
I patched line 68. I also adapted the existing tests so that they fail under the current code by swapping the first two observations in `\test\contrasts.jl`.
