### ISSUE TITLE
`@rexport using StatsBase, DataFrames` decision

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/StatsModels.jl#43]
I would like to get some feedback on whether StatsModels should `@reexport` StatsBase and DataFrames.

DataFrames `@reexport using CategoricalArrays, Missings`
Since StatsModels can only be used with DataFrames, it makes sense for it to `@reexport using DataFrames`
In essence, 
```
using StatsModels
```
rather than
```
using DataFrames, StatsModels
```
Likewise, StatsModels are used to make statistical models which will 99% rely or should use `StatsBase.RegressionModel <: StatsBase.StatisticalModel`.

A normal pipeline currently uses:
```
using DataFrames, StatsBase, StatsModels, StatisticalModule
```
rather than
```
using StatsModels, StatisticalModule
```

**Comment by kleinschmidt** [comment]
One short-to-medium-term goal is to decouple this from DataFrames, so I think re-exporting that would be a mistake.  I don't see any reason not to re-export StatsBase though, but I haven't thought much about it.

I agree it can be a little annoying to have to `using` so many different packages, but I think that's better addressed by a separate, overarching "batteries" package (sort of like the `tidyverse` R package).

**Comment by Nosferican** [comment]
I believe as long as there are choices, for example, different provides of tabular frameworks then not to export any (or if applicable the base one with `AbstractTabularData` or what not). For `StatsBase` I believe is a no brainer since it is part of the process and just one provider. For now, my package does
```
@reexport using DataFrames, StatsBase, StatsModels
```
since there are all steps in the pipeline.

**Comment by Nosferican** [comment]
I believe the only issue would be the annoying `StatsBase.df` depreciation which hasn't been drop yet... I think that one is long overdue.

**Comment by nalimilan** [comment]
It would make sense to reexport StatsBase functions which are related to modeling. But I agree we shouldn't reexport DataFrames.

**Comment by Nosferican** [comment]
Sounds good. Any modification to these candidate?

```
StatisticalModel
adjr2
aic
aicc
bic
coef
coefnames
coeftable
confint
deviance
dof
fit
fit!
loglikelihood
nobs
nulldeviance
r2
stderr
vcov
RegressionModel
dof_residual
fitted
modelmatrix
model_response
predict
predict!
residuals
```

**Comment by nalimilan** [comment]
Looks good (I guess this corresponds to all functions defined in the `statsmodels.jl` file?). Can you make a PR?

**Comment by Nosferican** [comment]
Sure. As soon as #33 is merged I will re fork and work on that.

**Comment by Nosferican** [comment]
After some re-consideration... I think packages that rely on StatsModels will be overriding some of these which would require `import` rather than getting them through `using`... Thus the actually benefit would not be that great.
