### ISSUE TITLE
With no intercept, number of model matrix columns depend on type of dependent variable

### ISSUE THREAD

**Issue by piever** [JuliaStats/StatsModels.jl#48]
I found this surprising bug (which it turns out I'm relying on in my tests for the Cox regression...). The number of columns in the model matrix in the categorical no intercept case depend on the type of the dependent variable! I have no idea what is going on. To reproduce, you need [Survival](https://github.com/ararslan/Survival.jl). 

```julia
julia> using Survival, DataFrames, StatsModels

julia> df = DataFrame(week = 1:4, status = [false, false, true, true], cat = [1,2,3,4]);

julia> df[:event] = EventTime.(df[:week],df[:status]);

julia> categorical!(df, :cat);

julia> ModelMatrix(ModelFrame(@formula(week ~ 0 + cat), df)).m
4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

julia> ModelMatrix(ModelFrame(@formula(event ~ 0 + cat), df)).m
4×3 Array{Float64,2}:
 0.0  0.0  0.0
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0
```

I'm on DataFrames 0.11 and StatsModels master.

**Comment by kleinschmidt** [comment]
I suspect this has something to do with how the Terms are represented (with the response listed first). I’ll take a closer look later...

**Comment by kleinschmidt** [comment]
@piever, can you check if this is fixed on master?

**Comment by piever** [comment]
Yes, it's fixed! Kudos for the really nice work on the rewrite!
