### ISSUE TITLE
Make ModelFrame work with an iterable of named tuples

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/StatsModels.jl#5]
This started in JuliaStats/DataFrames.jl#1018, but probably more appropriate to discuss this here.

Maybe a first step would be to just add more constructors to `ModelFrame` that for now materialize an iterator of named tuples into a `DataFrame` and then call the existing constructor? I'm sure there could be a more elegant implementation, but that might get us started?

**Comment by kleinschmidt** [comment]
That seems like a good start. Then there's something to test against :)

A more elegant solution would be to create a function from a `ModelFrame` that can be applied to each tuple and return one row.

**Comment by davidanthoff** [comment]
Alright, I think this is now more or less implemented in Query. If you are on ``master`` for Query, and have done ``using Query``, you should be able to just use any iterable table like object as the source for e.g. a ``ModelMatrix`` here in this package (including e.g. ``DataFrame``, ``TypedTable`` etc.). The code for this is [here](https://github.com/davidanthoff/Query.jl/blob/master/src/sinks/sink_statsmodels.jl).

I think we should keep this issue open, though, because we should eventually move to a more efficient implementation, where we skip the intermediate construction of the ``DataTable`` object that I have in there right now.

**Comment by davidanthoff** [comment]
And another update: this whole interface now lives in https://github.com/davidanthoff/IterableTables.jl. With that package one can now use any of the data sources described in that package with ``StatsModels``.

**Comment by palday** [comment]
I think is basically addressed with the use of Tables API in Terms 2.0 (#71).
