### ISSUE TITLE
@formula broken in v0.2.4

### ISSUE THREAD

**Issue by richardkwo** [JuliaStats/StatsModels.jl#61]
```julia
julia> using StatsModels
julia> @formula(:z ~ 1)
```
I get error
`ERROR: ArgumentError: non-call expression encountered: :z`

However, previously I should get
`Formula: :z ~ 1`

**Comment by ararslan** [comment]
Variable names in formulas should be written without the leading `:`, e.g. `@formula(z ~ 1)`. That works for me with StatsModels 0.2.4.

**Comment by richardkwo** [comment]
@ararslan I used to be able to generate formula at runtime with
`@formula($(names(df)[1])~1)`
where `df` is a `DataFrame`. But now that will throw an error. Do you know an alternative?

**Comment by ararslan** [comment]
Use `@eval`:
```julia
julia> df = DataFrame(z=[1,2,3], y=[4,5,6]);

julia> @eval @formula($(names(df)[1]) ~ 1)
Formula: z ~ 1
```

**Comment by richardkwo** [comment]
That works. Thanks. Closing the issue.
