### ISSUE TITLE
Allow easier creation of formulas using lists of variable names

### ISSUE THREAD

**Issue by pdeffebach** [JuliaStats/StatsModels.jl#62]
I have a workflow in Stata that works well for me that I would like to port to Julia. In general, i want to produce pristine formatted tables in latex that require a decent amount of code to create. Additionally, we usually have one main specification (fixed effects and clustering) that we care about, so all we need really explore in our regressions is various independent and dependent variable combinations. To do this in stata I write a function that accepts a list of `y` variables and a list of `x` variables. 
```
foreach y 
    local regressors `y' `x' // the equivalent to creating a formula 
    regress `regressors'
    ... saving all the results and making a table in latex
end
```

The key thing here is that it is very easy to change the collection of `x` variables in your model. 

Using the `@formula` macro in Julia, this is difficult. The rhs of a model is relatively easy, since you can interpolate with `$y`, but I cannot figure out how to take a vector of symbols and coerce everything into a model that can be regressed. 

I wrote a macro that solves this problem a bit. 

```
df = DataFrame(rand(10,10))
macro g(x)
    rhs = Expr(:call)
    push!(rhs.args, :+)
    for i in x.args
        push!(rhs.args, i)
    end
    Meta.quot(rhs)
end
m1 = @formula(x1 ~ x3 + x4)
m2 = copy(m1)
m2.rhs = @g [x3, x4] # looks the same
lm(m1, df) # works
lm(m2, df) # works
```

However I understand that such direct interpolation is very fragile. For instance, this macro doesn't allow the `&` operator etc, and you all may be considering re-doing the whole way you parse macros. 

I am looking for guidance on a few ways forward. 

- To what extent could the simple macro I defined above be extended to cover more use cases?
- How do you envision config files to work with StatsModels? 
  - Say want to define a list of dependent variables at the top of my script and then perform many operations on them, that don't involve StatsModels (summary statistics etc). How should I define these lists of variables in a dataset at the top of my script so that I can make a formula with this existing list?

**Comment by nalimilan** [comment]
The easiest and most robust approach is probably to create a string, and call `eval(parse(...))` on it.

**Comment by pdeffebach** [comment]
Okay so here is a workflow. 

```
struct Specification 
   controls 
   fixed_effects
   treatment 
   outcomes
end

# define control variables
controls = [:age, :baseline_income, :gender] 
# define fixed effects
fixed_effects = [:district]
# define treatment variable 
treatment = [:assigned] # could change later on to be actually received treatment
# define outcomes 
outcomes = [:income, :consumption, :health]

spec1 = Specification(...)

# make descriptive statistics 
... long table-making code that finds means for control and treated respondents.

# run regressions
function makeModel(y::Symbol, x::Vector{Symbol})
       s = "$y ~ "
       for i in x
           s = s * " + "
       s = s * "$i"
       end
       s
end

# trouble with this part
s = makeModel(:income, Specification.controls)
@formula(...something with s...)
```

If you could help me out with that last part, I would really appreciate it. I am having a lot of trouble working with the way `@formula` works. 

I think this solution is doable. My overall gripe is that `DataFrames` is all based around arrays of symbols, and it seems like a nice generic way for the interface to work. Do you think it makes sense for something similar to my `makeModel` to live in `StatsModels` so that there can be more consistency between the way DataFrames works and the way StatsModels works?

**Comment by nalimilan** [comment]
AFAICT the reason why `makeModel` is useful is that it's simple because it only handles a very specific scenario. That makes is poorly suited for integration in StatsModels. And a more general method would quickly become so complex that it would be equivalent to writing the formula by hand. Or am I missing something?

**Comment by pdeffebach** [comment]
Thanks, this is fine, and could definitely be handled in another module, especially because I'm probably under-estimating the variety of specifications people will want to use.
