### ISSUE TITLE
@formula macro does not take interpolation any more

### ISSUE THREAD

**Issue by mwsohn** [JuliaStats/StatsModels.jl#63]
I found that @formula does not take interpolation any more. For example,

```
lhs = :dis
fm = @formula($lhs ~ 1)
```

generates the following error message:

ArgumentError: non-call expression encountered: $(Expr(:$, :lhs))
include_string(::String, ::String) at loading.jl:522
include_string(::String, ::String, ::Int64) at eval.jl:30
include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N} where N) at eval.jl:34
(::Atom.##102#107{String,Int64,String})() at eval.jl:82
withpath(::Atom.##102#107{String,Int64,String}, ::Void) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
hideprompt(::Atom.##101#106{String,Int64,String}) at repl.jl:67
macro expansion at eval.jl:80 [inlined]
(::Atom.##100#105{Dict{String,Any}})() at task.jl:80

Is it a bug or an intended change? If this behavior is intended, is there an alternative?

**Comment by kleinschmidt** [comment]
It's intended, since we're planning on changes that require `@formula` to run at "compile" time.  You can use `@eval @formula($lhs ~ 1)` instead.

**Comment by pdeffebach** [comment]
For reference, you can also do this:

```
function expandargs(x)
    :(+$(x...))
end
rhs = [:x1, :x2, :x3]
lhs = :y
@eval @formula($lhs ~ $(expandargs(rhs)))
```
