### ISSUE TITLE
update() method

### ISSUE THREAD

**Issue by DominiqueMakowski** [JuliaStats/StatsModels.jl#73]
I originally posted this [here](https://github.com/JuliaStats/GLM.jl/issues/249), but it might a more general feature that applies to all models. 

There doesn't seem to be, currently, an update() method similar to R's that would allow to very easily re-fit a model with only changing specific parameters (for instance, the data).

```julia
model = lm(@formula(y ~ x), data1)
update!(model, data2)
```
If such method is not in the plans, how could I achieve a refitting with a different dataset (but everything else the same) using the current tools? Thank you!

**Comment by Nosferican** [comment]
Depending on the model, you could try
```
model = deepcopy(model)
setfield!(model, :field, value)
fit!(model)
```
My package does so for fitting related models, for random effects fitting the between, the within, and finally the random effects.

**Comment by DominiqueMakowski** [comment]
@Nosferican Thanks for your answer!

Unfortunately, I tried but it didn't work:

```julia
using GLM, DataFrames
model = lm(@formula(y ~ Var1), DataFrame(y=[0, 1, 2, 3], Var1=[2, 3, 3.5, 4]))

newdata = DataFrame(y=[3, 2, 1, 0], Var1=[2, 3, 3.5, 4])

model2 = deepcopy(model)
setfield!(model2, :data, newdata)
fit!(model2)
```
```
ERROR: type DataFrameRegressionModel is immutable
```

I am not sure how to set the things properly to re-fit with different data. Thanks!

**Comment by Nosferican** [comment]
I don't think that works nicely with the GLM, but will probably work best with higher order packages. GLM is basically just Fisher scoring, useful for basic things. Changing the data will require the whole pipeline so you would be best served with just a wrapper and passing the `data` as the only argument.

**Comment by DominiqueMakowski** [comment]
That's very unfortunate! I needed to implement a function equivalent of that of the [R's psycho](https://github.com/neuropsychology/psycho.R) package that takes a model (a GLM), extracts and standardize the data and refit the exact same model with standardized data to derive "true" standardized coefs :/

Wouldn't it be possible to dig into the GLM object, (I guess it's somewhere near `model.mf.df`?), change this field and refit?

**Comment by Nosferican** [comment]
Not with GLM, but for standardizing the data and such GLM would not be a good tool. I apply various transformations to the linear predictor for models (e.g., method of alternating projections for the within estimator to absorb fixed effects), but do so in my packages. You could try long-hand doing the `ModelFrame` and `ModelMatrix` and passing it...
With StatsModels Terms2 a package might be able to define a pipeline which does standardization before fitting as one of the pre-fitting transformations.

**Comment by nalimilan** [comment]
> Wouldn't it be possible to dig into the GLM object, (I guess it's somewhere near `model.mf.df`?), change this field and refit?

Yes, you can access the formula used to fit a `DataFrameRegressionModel` (including GLMs fitted from a formula + data frame) using `m.mf.f`, and the data with `m.mf.df`. Then you should be able to re-fit the model.

**Comment by DominiqueMakowski** [comment]
Ok right. Unfortunately, it seems inconvenient in the scenario of non-default family, links or other parameters... Thus I keep wondering about the generalisation of such method: I don't see the technical limitation (with my poor knwoledge) of an `update()` method that takes, beyond the model itself, the same parameters than the model filled with `nothing` by default. The update method would replace all the `nothings` with the parameters extracted from the model, keep the ones specified by the user and refit the model. Isn't that feasible?

**Comment by Nosferican** [comment]
You can wrap the default parameters with a struct with various constructors or using `Parameters.jl` and then just pass these to a function that does that (easy to implement, straightforward). However, I feel like that shouldn't be a general utility, I use it in my package because I need it in special cases for selected models and my `Struct` was designed to handle that functionality (GLM is not) to some extend (i.e., apply various transformations to the data and change certain options).

**Comment by DominiqueMakowski** [comment]
It's quite heavily used in R, so I supposed it would have some general utility in Julias as well (simply to build several models without having to re-specify every parameter every time which can be verbose). By your package you mean ecnonometric? Thanks for your help though, I'll try to work something out :)

**Comment by Nosferican** [comment]
Maybe something like,
```
using DataFrames, StatsModels, GLM, Parameters, Random
Random.seed!(0)
data = DataFrame(hcat(repeat(1:3, inner = 3), rand(9,3)))
m_formula = @formula(x2 ~ x3 + x4)
transformations = [(data -> let df = aggregate(data, :x1, mean)
                            names!(df, [:x1, :x2, :x3, :x4])
                            return df
                        end),
                   (data -> let df = aggregate(data, :x1, median)
                            names!(df, [:x1, :x2, :x3, :x4])
                            return df
                        end)]
models = glm.(Ref(m_formula),
              (transformation(data) for transformation in transformations),
              Ref(Normal()))
```
could help you.
It uses the same `Formula`, and `Distribution`, but different data based on a collection of transformations.

Aye, Econometrics.jl, but haven't been updated and ported everything to it. Waiting on StatsModels Terms 2 and getting some time to finish it up.

**Comment by DominiqueMakowski** [comment]
For now, I've managed to make it work for my use case (with [this](https://github.com/neuropsychology/Psycho.jl/blob/f15e20d30b71849f8f06171af8f11544b48d960e/src/report/LM.jl#L11) manual refitting), but it clearly needs a more general solution... Thanks for your leads!

**Comment by DominiqueMakowski** [comment]
Based on @kleinschmidt comments in the #75 issue, I agree with the feeling that StatModels should be "transformation agnostic", and that transformations should be preferably made explicitly by the user before fitting the model.

I also understand that not storing the original dataset  (as it is done in Mixedmodels) used for fitting the model makes sense from a performance perspective, as users rarely re-extract the data from the models, thus possibly using a lot of memory space "for nothing".

However, this absence of data could prevent the developpment of an independent ecosystem of packages, using only end models to do further domain-specific things (plotting, transforming, refitting...), and it also prevents, I think, the developpment fo a complete `update()` method (although there surely are workarounds with model matrices but it could be limited). In general, I feel like the majority of people using StatModels would not care (from a computational and memory perspective and my very personal feeling) having the data stored in the model, just like in R. However, for the remaining users, fitting models on big data and caring about memory usage and performance, there could be an argument (for instance, `light=true`) that would return a light model with only the bare necessities for diagnostic and predictions.

**Comment by nalimilan** [comment]
Would it be a big problem to require such methods to take the data as an argument? We could also support the `light` argument, but defaulting to `true`. In general, I'd be inclined to avoid storing information that isn't strictly necessary in models, especially as very large datasets are increasingly common.

**Comment by DominiqueMakowski** [comment]
You're probably right about the very large datasets and no, I believe requiring data for "post-hoc" methods wouldn't be a major problem. So for instance for the update method, you would recommend the data as a mandatory argument? 

```julia
model = lm(@formula(y ~ x), data1)
update!(model, @formula(y ~ x), data=data2)
update!(model, @formula(y ~ x + x2), data=data1)
```

**Comment by nalimilan** [comment]
Yeah, except if people passed `light=false` (or a similar argument) to the first call.
