### ISSUE TITLE
An alternative representation of Terms?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/StatsModels.jl#8]
Thanks for all the work on this, @kleinschmidt .  

Do you have a plan of how you want to rework the `Terms` type?  

I have been thinking that many of the kludges like the `response` member being a `Bool` with the unstated assumption that it corresponds to the first of the `eterms` can be bypassed.  The response member should be something like `Formula.lhs` and the `terms` member should be an array of types like `Formula.rhs`.  If we retain a `1` as a term in `terms` then the `intercept` member can be replaced by an expression like `1 in terms`.  It would then only be necessary to sort the terms according to order and decide how to evaluate them in the ModelFrame where dispatching on the type would be helpful.

These are just a few thoughts.  If you have a better scheme in mind then we should go with that.

**Comment by nalimilan** [comment]
By the way, we should allow for several terms on the LHS, which is needed e.g. for partial least squares regression.

**Comment by kleinschmidt** [comment]
I've done a bit of work in this direction actually, and I think we're basically on the same page. It's not quite ready for review but the idea is to get rid of `Terms` completely, and just use a `Term` tree that gets transformed based on the data schema and then generates model matrix columns or rows by traversing the tree. If you're curious I'm working on this in [dfk/modelmatrix2](https://github.com/JuliaStats/StatsModels.jl/blob/dfk/modelmatrix2/src/modelmatrix2.jl) which is built on top of #4, but it's very rough still.

**Comment by kleinschmidt** [comment]
Closed by #71
