### ISSUE TITLE
Are offsets supported?

### ISSUE THREAD

**Issue by galenlynch** [JuliaStats/StatsModels.jl#92]
I would like to fit a GLM model with poisson distribution response variables, and also use an offset. I can't tell from the documentation or the code if I can use a `@formula` to include an offset. Are offsets supported, and if so how can I use them?

**Comment by lbittarello** [comment]
[GLM.jl](https://github.com/JuliaStats/GLM.jl) allows offsets: check the example [here](https://github.com/JuliaStats/GLM.jl/blob/84da7f178589ebd5aa131e92be5aff8baa9a9636/test/runtests.jl) (line 166). Note that the offset is not part of the formula.

[Microeconometrics.jl](https://github.com/lbittarello/Microeconometrics.jl) allows offsets too: check the example [here](https://github.com/lbittarello/Microeconometrics.jl/blob/master/test/runtests.jl) (line 182). The syntax is a little different though.

**Comment by nalimilan** [comment]
We probably need to standardize on a way of passing an offset variable just like for weights and panel grouping information (https://github.com/JuliaStats/StatsModels.jl/issues/90).

**Comment by galenlynch** [comment]
Thanks for the tips! I ended up making a PR to GLM.jl to document the offset keyword argument. Standardizing offset in StatsModels.jl would be great, if possible.
